# ==========================================================
# CONFIGURACIÓN DE BASE DE DATOS - REGISTRADURÍA NOBSA
# ==========================================================

# Motor activo (Aunque tu clase ya está fija para Postgres, es buena práctica tenerlo)
db.engine=postgresql

# Credenciales de PostgreSQL Local [cite: 264, 265, 266]
postgresql.url=jdbc:postgresql://localhost:5432/registraduria_nobsa
postgresql.user=postgres
postgresql.password=123456